from typing import Literal

GWASLAB_CHROM_COL = "CHR"
GWASLAB_POS_COL = "POS"
GWASLAB_EFFECT_ALLELE_COL = "EA"
GWASLAB_NON_EFFECT_ALLELE_COL = "NEA"
GWASLAB_INFO_SCORE_COL = "INFO"
GWASLAB_ODDS_RATIO_COL = "OR"
GWASLAB_BETA_COL = "BETA"
GWASLAB_EFFECT_ALLELE_FREQ_COL = "EAF"
GWASLAB_SAMPLE_SIZE_COLUMN = "N"
GWASLAB_STATUS_COL = "STATUS"

GwaslabKnownFormat = Literal["gwaslab", "regenie"]
